// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieAPI.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20240816111759_RemoveImageUrl")]
    partial class RemoveImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieAPI.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImage")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "",
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Genre = "Action,Drama,Thriller",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "",
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
                            Genre = "Sci-Fi,Action,Thriller",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "",
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            Genre = "Drama,Romance",
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "",
                            Description = "Seventy-eight year old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.",
                            Genre = "Animation,Adventure,Family",
                            Title = "Up"
                        },
                        new
                        {
                            Id = 5,
                            CoverImage = "",
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Genre = "Drama",
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 6,
                            CoverImage = "",
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Genre = "Crime,Drama",
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 7,
                            CoverImage = "",
                            Description = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            Genre = "Crime,Drama",
                            Title = "The Godfather: Part II"
                        },
                        new
                        {
                            Id = 8,
                            CoverImage = "",
                            Description = "Eight years after the Joker's reign of anarchy, Batman is forced from his exile with the help of the enigmatic Selina Kyle to save Gotham City from the brutal guerrilla terrorist Bane.",
                            Genre = "Action,Drama,Thriller",
                            Title = "The Dark Knight Rises"
                        },
                        new
                        {
                            Id = 9,
                            CoverImage = "",
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Genre = "Adventure,Drama,Sci-Fi",
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 10,
                            CoverImage = "",
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Genre = "Action,Adventure,Drama",
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 11,
                            CoverImage = "",
                            Description = "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
                            Genre = "Biography,Drama,History",
                            Title = "Braveheart"
                        },
                        new
                        {
                            Id = 12,
                            CoverImage = "",
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            Genre = "Drama,War",
                            Title = "Saving Private Ryan"
                        },
                        new
                        {
                            Id = 13,
                            CoverImage = "",
                            Description = "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Genre = "Biography,Drama,History",
                            Title = "Schindler's List"
                        },
                        new
                        {
                            Id = 14,
                            CoverImage = "",
                            Description = "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Genre = "Crime,Drama,Thriller",
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 15,
                            CoverImage = "",
                            Description = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            Genre = "Drama",
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 16,
                            CoverImage = "",
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Genre = "Action,Sci-Fi",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 17,
                            CoverImage = "",
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Genre = "Adventure,Drama,Fantasy",
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 18,
                            CoverImage = "",
                            Description = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            Genre = "Adventure,Drama,Fantasy",
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 19,
                            CoverImage = "",
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            Genre = "Adventure,Drama,Fantasy",
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 20,
                            CoverImage = "",
                            Description = "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
                            Genre = "Action,Adventure,Fantasy",
                            Title = "Star Wars: Episode IV - A New Hope"
                        },
                        new
                        {
                            Id = 21,
                            CoverImage = "",
                            Description = "After the Rebels are overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jeditraining with Yoda, while his friends are pursued by Darth Vader and a bounty hunter named Boba Fett all over the galaxy.",
                            Genre = "Action,Adventure,Fantasy",
                            Title = "Star Wars: Episode V - The Empire Strikes Back"
                        },
                        new
                        {
                            Id = 22,
                            CoverImage = "",
                            Description = "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.",
                            Genre = "Action,Adventure,Fantasy",
                            Title = "Star Wars: Episode VI - Return of the Jedi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
